<?php

namespace App\Http\Controllers\Api\Mobile;

use App\Actions\Fortify\DetermineAccountBlockReason;
use App\Actions\Mobile\DecodePasskeyVerificationPayload;
use App\Enums\LoginContext;
use App\Http\Controllers\Controller;
use App\Http\Resources\MobileAuthResource;
use App\Models\User;
use Illuminate\Http\JsonResponse;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Hash;
use Illuminate\Validation\ValidationException;
use Laravel\Passkeys\Actions\GenerateVerificationOptions;
use Laravel\Passkeys\Actions\VerifyPasskey;
use Laravel\Passkeys\Exceptions\InvalidPasskeyException;
use Laravel\Passkeys\Support\WebAuthn;

/**
 * Mobile-only authentication (PRD section 9): issues a Sanctum personal
 * access token instead of the web's session-cookie login, for both the
 * password and passkey login methods Fortify already supports.
 *
 * Passkey login here does not use Fortify's own PasskeyLoginController: that
 * controller stores verification options in the session between the
 * "options" and "verify" calls, but /api/mobile is a stateless, token-based
 * API with no session middleware. Instead, the options generated by
 * Fortify's own GenerateVerificationOptions action are serialized and
 * handed to the client, which echoes them back verbatim on the verify
 * call — the same round-trip, just carried by the client instead of the
 * session. VerifyPasskey (also Fortify's own action) still performs the
 * real WebAuthn assertion check; nothing about the cryptographic
 * verification is reimplemented or weakened by skipping the session.
 */
class MobileAuthController extends Controller
{
    public function passkeyLoginOptions(GenerateVerificationOptions $generate): JsonResponse
    {
        $options = $generate();

        return response()->json([
            'options' => WebAuthn::toBrowserArray($options),
            'options_token' => WebAuthn::toJson($options),
        ]);
    }

    public function passkeyLogin(
        Request $request,
        DecodePasskeyVerificationPayload $decode,
        VerifyPasskey $verify,
        DetermineAccountBlockReason $blockReason,
    ): JsonResponse {
        $validated = $request->validate([
            'credential' => ['required', 'array'],
            'credential.id' => ['required', 'string'],
            'credential.rawId' => ['required', 'string'],
            'credential.type' => ['required', 'string', 'in:public-key'],
            'credential.response' => ['required', 'array'],
            'options_token' => ['required', 'string'],
            'device_name' => ['required', 'string', 'max:255'],
        ]);

        [$credential, $options] = $decode($validated['credential'], $validated['options_token']);

        try {
            $passkey = $verify($credential, $options);
        } catch (InvalidPasskeyException $exception) {
            throw ValidationException::withMessages([
                'credential' => $exception->getMessage(),
            ]);
        }

        /** @var User $user */
        $user = $passkey->user;

        if ($reason = $blockReason($user, LoginContext::MOBILE)) {
            throw ValidationException::withMessages([
                'credential' => [$reason],
            ]);
        }

        $token = $user->createToken($validated['device_name']);

        return response()->json(MobileAuthResource::make($user, $token));
    }

    public function login(Request $request, DetermineAccountBlockReason $blockReason): JsonResponse
    {
        $credentials = $request->validate([
            'email' => ['required', 'email'],
            'password' => ['required', 'string'],
            'device_name' => ['required', 'string', 'max:255'],
        ]);

        $user = User::where('email', $credentials['email'])->first();

        if (! $user || ! Hash::check($credentials['password'], $user->password)) {
            throw ValidationException::withMessages([
                'email' => __('These credentials do not match our records.'),
            ]);
        }

        if ($reason = $blockReason($user, LoginContext::MOBILE)) {
            throw ValidationException::withMessages([
                'email' => [$reason],
            ]);
        }

        $token = $user->createToken($credentials['device_name']);

        return response()->json(MobileAuthResource::make($user, $token));
    }

    /**
     * Revoke the token used to authenticate the current request, logging
     * this device out without affecting the user's other sessions/devices.
     */
    public function logout(Request $request): JsonResponse
    {
        $request->user()->currentAccessToken()->delete();

        return response()->json(['message' => 'Logged out.']);
    }
}
